spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_GOOGLE_USERNAME}
    password: ${MAIL_GOOGLE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true
  kafka:
    bootstrap-servers: kafka:29092, localhost:9092
    consumer:
      group-id: "1"
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8081




